In [1]:
import pandas as pd

# Series

In [2]:
# 生成一个Series

# 创建一个 Pandas Series（一维带标签的数组），包含从10到19的整数，索引默认从0开始递增
ser_obj = pd.Series(range(10, 20))      # 默认索引 0-9

# 打印输出左边一列为索引，右边一列为值；且输出会带有类型
print(ser_obj)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [8]:
# 获取数据
print(ser_obj.values)       # values实际是ndarray
print(type(ser_obj.values)) # <class 'numpy.ndarray'>
# 获取索引
print(ser_obj.index)        # 内部自带的类型--RangeIndex

ser_obj.dtype               # dtype('int64')

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [6]:
print(ser_obj[0])
print(ser_obj[9])
ser_obj[9]
# 访问不存在的索引下标会保keyerror

10
19


np.int64(19)

In [10]:
print(ser_obj * 2)      # 元素级乘法
print('-' * 50)
print(ser_obj > 15)     # 返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
--------------------------------------------------
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [16]:
# 字典变为series，索引是字典的key，value是字典的value，感受非默认序列

year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-' * 50)

print(ser_obj2.index)       # Index([2001, 2005, 2003], dtype='int64')
print('-' * 50)

print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [17]:
print(ser_obj2.name)
print(ser_obj2.index.name)
print('-' * 50)

# Series名字
ser_obj2.name = 'temp'
# 索引名字
ser_obj2.index.name = 'year1'
print(ser_obj2.head())

None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# DataFrame

In [18]:
import numpy as np
# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3, 4)))         # 默认索引是0-2
print(t)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [19]:
# random normal：随机正态分布
array = np.random.randn(5, 4)
print(array)
print('-' * 50)

df_obj = pd.DataFrame(array)
print(df_obj.head())            # 默认显示前5行

[[ 2.15006747 -0.73646461 -0.12987079  0.61789892]
 [-0.65004641  1.16641438 -0.05665294 -0.85829814]
 [-1.5900759  -0.6062506  -1.08075971  0.71463165]
 [-0.87355229  1.97948684  0.99933673  0.55255404]
 [ 0.70905673 -0.67263455  3.05830406  0.82161155]]
--------------------------------------------------
          0         1         2         3
0  2.150067 -0.736465 -0.129871  0.617899
1 -0.650046  1.166414 -0.056653 -0.858298
2 -1.590076 -0.606251 -1.080760  0.714632
3 -0.873552  1.979487  0.999337  0.552554
4  0.709057 -0.672635  3.058304  0.821612


In [20]:
t.loc[0]            # 单独把某一行取出来，类型是Series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [21]:
# 列表套字典 变df
d2 = [{"name": "xiaohong", "age": 32, "tel": 10010}, {"name": "xiaogang", "tel": 10000}, {"name": "xiaohong", "age": 22}]
df6 = pd.DataFrame(d2)
print(df6)                  # 缺失值会用Nan填充
print(type(df6.values))     # ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaohong  22.0      NaN
<class 'numpy.ndarray'>


In [22]:
pd.Series(1, index=list(range(3, 7)), dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [23]:
# df中不同列可以是不同的数据类型，同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'wangdao'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [24]:
print(df_obj2.index)        # 行索引，重点
# df_obj2.index[0] = 2       不可以单独修改某个索引值
print(df_obj2.columns)      # 列索引，重点
df_obj2.dtypes

Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')


A             int64
B    datetime64[us]
C           float32
D             int32
E               str
F               str
dtype: object

In [26]:
# 感受日期，初始化df，设置行索引，列索引
# 起始：‘20130101’（2013-01-01） periods=6:一共生成6个时间点     默认时间间隔：1天
dates = pd.date_range('20130101', periods=6)    # 默认freq=‘D’，即 天
print(dates)
print('-' * 50)

# list('ABCD')：字符串是可迭代对象，list()会逐个取出字符生成列表
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-' * 50)
print(df.index)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')
                   A         B         C         D
2013-01-01  0.096432 -0.773764  1.700594 -0.176208
2013-01-02  0.723697 -0.807533  1.112756 -0.794012
2013-01-03  0.238453  1.050013  0.075960 -0.537996
2013-01-04 -1.611871 -0.626314  0.812240  0.438745
2013-01-05  0.677025  0.692210 -0.051165  0.867907
2013-01-06 -0.276573  0.073588 -0.402218 -0.640940
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')


In [33]:
print(df_obj2)
print('-' * 50)

print(type(df_obj2))
print('-' * 50)
# pd中使用索引名来取某一列
print(df_obj2['B'])
print('-' * 50)
# 取某一行
print(df_obj2.loc[0])
print('-' * 50)
# 把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[us]
--------------------------------------------------
A                      1
B    2019-09-26 00:00:00
C                    1.0
D                      1
E                 Python
F                wangdao
Name: 0, dtype: object
--------------------------------------------------
<class 'pandas.Series'>


In [30]:
# 增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
# 输出DataFrame前5行数据（默认5行）
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [31]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
