# 列表如何转为ndarray

In [1]:
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [5]:
one_array = np.array(list1)
print(type(one_array))
# ndarray没有逗号，list列表有逗号
print(one_array)

<class 'numpy.ndarray'>
[1 2 3 4]


# ndarray与Python原生list运算效率对比

In [3]:
import random
# python内置time库
import time
import numpy as np

# 随机一亿个数据
a = []
# 10**8 
for i in range(100000000):
    # random.random()生成[0.0, 1.0)之间的随机浮点数
    a.append(random.random())
print('随机完毕')

随机完毕


In [4]:
b = np.array(a)
print('转换完毕')

转换完毕


In [7]:
# ndarray的计算效率优于python的list
# time.time() 返回时间戳：从1970-01-01 00:00:00 UTC 到现在的秒数（浮点数）
t1 = time.time()
# python内置函数sum()直接对数字列表求和
# sum(可迭代对象, start=0) 可迭代对象：list、tuple、range、numpy数组等都可以；start：额外加上的初始值（可选）
# 例：print(sum([1, 2, 3]), 100)  1 + 2 + 3 + 100 = 106
sum1 = sum(a)
t2 = time.time()

# numpy运算更快
t4 = time.time()
# numpy求和函数，如果b是numpy ndarray，优先np.sum()，底层优化，支持多维、指定维度求和
# 例：print(np.sum(arr, axis=0))  axis=0，沿着行方向进行压缩，即按列求和    axis：控制沿着哪个维度相加，内置sum()没有axis参数
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

1.542936086654663 0.18390202522277832


In [8]:
t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
print(range(10))
print(type(range(10)))
t2 = np.array(range(10))
print(t2)
print(type(t2))

range(0, 10)
<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [10]:
t3 = np.arange(0, 10, 2)    # 等价于range(0, 10, 2)，返回ndarray；arange = array + range
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [11]:
# 二维列表转ndarray
import numpy as np
list2 = [[1, 2], [3, 4], [5, 6]]

two_array = np.array(list2)
print(type(two_array))
print(two_array)
# 列表的输出是有逗号的，ndarray的输出是没有逗号的
print(list2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [12]:
# 将ndarray转换为列表
two_array.tolist()

[[1, 2], [3, 4], [5, 6]]

# 4.3 常用属性

In [14]:
# 看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

two_array = np.array(list2)
# 获取数组的维度
# ndim：n-dimension
print(two_array.ndim)   # 2维
# 获取数组的形状（行， 列）
print(two_array.shape)  # 3行2列

# 数组的大小，即共有多少个数据元素
print(two_array.size)
# 数据类型（data type）
print(two_array.dtype)  # 默认int32， 4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int64


# 4.4 调整数组的形状

In [18]:
four = np.array([[1, 2, 3], [4, 5, 6]])

print(id(four))
print(four)
four1 = four
print(id(four))

4376950896
[[1 2 3]
 [4 5 6]]
4376950896


In [19]:
four.shape = (3, 2)
# ndarray也是一个可变数据类型，数据改变不会改变地址
print(id(four))
print(id(four1))
print(four)
print(four1)

4376950896
4376950896
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [26]:
print('-' * 50)
# 返回的是一个新的数组，reshape后的id地址与之前的id地址不一样
# shape获取数组的形状，reshape改变数组的形状
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
4376950896
4376672656


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 将多维数组变为一维数组 (6,)：变为一维数组（长度为6）；默认情况下‘C’以行为主的顺序展开，‘F'（Fortran风格）意味着以列的顺序展开
# 展平方式一
five = four.reshape((6,), order='C')
# 展平方式二
six = four.flatten()    # 展开成一维数组
print(five)
print('-' * 50)
print(six)

# print(five.reshape(3, 2))

[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [28]:
seven = five.reshape(3, 2)
seven

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
print('-' * 50)
t = np.arange(24)
print(t)
print(f'shape{t.shape}')    # shape(24,)
print(t.ndim)               # 1

# 此为标准写法，也可简写为 t.reshape(4, 6)
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)             # （4， 6）

--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [31]:
# 转成三维
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [32]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
# ndim：n-dimension 有多少维度
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


# 4.5 数组转为列表

In [33]:
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))

<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# 5. numpy的数据类型

In [34]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度，dtype设置数据类型

# 结果1表示1字节
print(f.itemsize)   # 1
# 获取数据类型
print(f.dtype)      # int8

1
int8


In [35]:
f[4] = f[4] + 1     # 溢出
f[4]

/var/folders/pb/p_cly9gj3xv6l7083h32ln_80000gn/T/ipykernel_9869/1546673322.py:1: RuntimeWarning: overflow encountered in scalar add
  f[4] = f[4] + 1     # 溢出


np.int8(-128)

In [36]:
# 调整数据类型
# as type作为某种类型，即转换为某种类型；astype()整个numpy数组批量类型转换，只能用于ndarray
f1 = f.astype(np.int64)
print(f1.dtype)
# 结果8表示占用8个字节
print(f1.itemsize)      # 8
print('-' * 50)

int64
8
--------------------------------------------------


In [37]:
random.random()

0.9552318535801769

In [38]:
# round(数值, 小数位数)：四舍五入保留指定位小数
# python内置函数round只能处理单个数值
print(round(random.random(), 2))

arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)     # 8表示数据占用8个字节
print(arr.dtype)

# numpy的round函数专门处理数组（批量），也能处理单个数字
print(np.round(arr, 2))

0.13
[2.80662895e-04 8.49871573e-01 9.68823053e-01 1.02606545e-01
 9.50181458e-01 2.44404089e-01 7.07176362e-01 6.51077552e-01
 4.64380648e-01 4.06293108e-01]
8
float64
[0.   0.85 0.97 0.1  0.95 0.24 0.71 0.65 0.46 0.41]


# 数组和数的运算

In [39]:
# 列表不可以和整数相加，但ndarray可以
[1, 2, 3] + 5

TypeError: can only concatenate list (not "int") to list

In [40]:
# 由于列表的广播机制，在运算过程中，加减乘除的值被广播到所有元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print('-' * 50)
t2 = t1.tolist()
# ndarray中每个元素都被+2
print(t1 + 2)
print('-' * 20)
print(t1 * 2)
print('-' * 20)
print(t1 / 2)
# 无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------------------------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# ndarray与ndarray的运算

In [41]:
# 形状相同，才可以进行加减乘除
# 先生成0-23的一维数组，再重塑为6行4列的二维数组，最终赋值给变量t1
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
# 不是矩阵乘法，是对应位置相乘
print(t1 * t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [45]:
# shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(18).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)  # ValueError: operands could not be broadcast together with shapes (4,6) (3,6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,6) 

In [46]:
# 一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))   # 虽是一维数组，但用二维表示（1行6列）
print(t2.shape)
print(t1)
print(t2)
# 注意这个差值，是这个一维数组与二维数组的每行进行计算
t1 - t2

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [47]:
(t1 - t2).shape

(4, 6)

In [48]:
# 行数或列数相同的一维数组和多维数组可以进行计算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
# 二维数组t1的每列与一维数组t2进行计算
t1 - t2

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [49]:
# 随机3维数组
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
a - b

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

##  结论：nidm要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

In [50]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('-' * 50)
# sum沿着指定axis‘压缩合并’这个维度，这个维度直接消失
print(np.sum(a, axis=0))    # [5 7 9]   行压缩
print('-' * 50)
print(np.sum(a, axis=1))    # [ 6 15]   列压缩
print('-' * 50)
print(np.sum(a))        # 21
print('-' * 50)

[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[5 7 9]
--------------------------------------------------
[ 6 15]
--------------------------------------------------
21
--------------------------------------------------


In [53]:
a = np.arange(24).reshape((2, 3, 4))

b = np.sum(a, axis=0)
print('-' * 50)
print(b)
print(b.shape)

c = np.sum(a, axis=1)
print('-' * 50)
print(c)
print(c.shape)

d = np.sum(a, axis=2)
print('-' * 50)
print(d)
print(d.shape)

--------------------------------------------------
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)
--------------------------------------------------
[[12 15 18 21]
 [48 51 54 57]]
(2, 4)
--------------------------------------------------
[[ 6 22 38]
 [54 70 86]]
(2, 3)


# 索引和切片

In [54]:
import numpy as np
a = np.arange(10)

print(a[0], a)

print(a[2:])

# 与列表切片一致；左闭右开，步长为2，即间隔为1
print(a[2:8:2])

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [55]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('-' * 50)
print(t1[1])        # 等价于 print(t1[1,:]；取一行数据（一行代表是一条数据，索引也是从0开始）
print('-' * 50)

print(t1[1:])       # 取连续行，从下标为1的行到末尾行
print('-' * 50)

print(t1[1:3, :])   # 取连续行，下标为1和下标为2的行，也是左闭右开
print('-' * 50)

# 从二维Numpy数组t1中，按顺序提取行索引为 0， 2， 3的三行（保留所有列），然后打印这个子数组
# 属于花式索引（整数数组索引）t1[[0, 2, 3]] == t1[[0, 2, 3], :]
print(t1[[0, 2, 3]])    # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[ 6  7  8  9 10 11]
--------------------------------------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
--------------------------------------------------
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [57]:
# 看列表
t2 = np.arange(24).reshape(4, 6).tolist()
print(t2[2])
# 原生列表不支持numpy花式索引[[0, 2, 3]]
t2[[0, 2, 3]]

[12, 13, 14, 15, 16, 17]


TypeError: list indices must be integers or slices, not list

In [58]:
# 取列下标为1的这一列
print(t1[:, 1])
print('-' * 50)
# 取从列下标为1的列到末尾列
print(t1[:, 1:])
print('-' * 50)

# 这里是取0， 2， 3列，注意观察
print(t1[:, [0, 2, 3]])     # 取不连续的多列
print('-' * 50)
print(t1[2, 3])     # 取某一个值，类似于python中的 arr[2][3]
print('-' * 50)
# numpy高级索引（配对取单个元素）；两个长度相等的索引列表一一配对，取出坐标（行号，列号）的单个元素；(0, 0) (1, 1) (1, 3)
print(t1[[0, 1, 1], [0, 1, 3]])

# 左闭右开，取1-2行，1-3列
t1[1:3, 1:4]

[ 1  7 13 19]
--------------------------------------------------
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
--------------------------------------------------
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
--------------------------------------------------
15
--------------------------------------------------
[0 7 9]


array([[ 7,  8,  9],
       [13, 14, 15]])

# 修改值

In [59]:
import numpy as np
 
t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
4454226256
--------------------------------------------------


In [63]:
# 修改某一行的值，支持批量修改
t[1, :] = 0

# 修改某一列的值
t[:, 1] = 0

# 修改连续多行
t[1:3, :] = 0

# 修改连续多列
t[:, 1:4] = 0

# 修改多行多列，取下标1-2行，下标2-4列
t[1:3, 2:5] = 0

# 修改多个不相邻的点
t[[0, 1], [1, 3]] = 0       # t[0,1] = 0, t[1, 3] = 0

# 可以根据条件修改，比如讲小于10的值改掉
t[t<10] = 0

# python中 & 是位运算符，作用于二进制位，and 是逻辑运算符，判断真假
# 使用逻辑判断
# np.logical_and, np.logical_or, np.logical_not
# numpy中布尔条件必须用 & | ~ (位运算符)，不能直接用and 、or
t[(t > 2) & (t < 6)] = 0        # 逻辑与，and
t[(t < 2) | (t > 6)] = 0        # 逻辑或，or
t[~(t > 6)] = 0                 # 逻辑非
print(t)

# 对numpy数组t执行‘裁剪’操作-将数组中小于10的元素替换为10，大于18的元素替换为18，介于10-18之间的元素保持不变，最后将裁剪后的数组重新赋值给t
t = t.clip(10, 18)
print(id(t))
t

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
4596214704


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [64]:
t = np.arange(24).reshape(4, 6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [65]:
# python的三目运算
a = 10
b = 15
# python中没有a > b ? a : b这种三目运算符，只有以下三目运算符
c = a if a > b else b
c

15

In [70]:
# 拓展：三目运算符（np.where(condition, x, y）满足条件condition，输出x，不满足则输出y
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score > 80, True, False)
print(result)

[[80 88]
 [82 81]
 [75 81]]
[[False  True]
 [ True  True]
 [False  True]]


In [71]:
# numpy中布尔索引 True表示保留该位置，False表示舍弃该位置
score[result] = 100
score

array([[ 80, 100],
       [100, 100],
       [ 75, 100]])

# 数据的添加、删除与去重

In [92]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
# np.append(arr, values, axis=None) 默认axis=None：先展平，再追加
print(np.append(a, [7, 8, 9]))
print('-' * 50)

# ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
# print(np.append(a, [7, 8, 9], axis=0))

# 这里的values必须与a维度相同
# 行添加
print(np.append(a, [[7, 8, 9]], axis=0))
print('-' * 50)
# 列添加
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print('-' * 50)
# 所有append操作返回新数组，原来数组不发生变化
print(a)

[1 2 3 4 5 6 7 8 9]
--------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]


In [89]:
b = np.array([[7, 8, 9]])
print(b.ndim)
print(b)

2
[[7 8 9]]


In [87]:
# np.insert(arr, obj, values, axis=None)    arr：原数组；obj：插入位置索引（下标）；values：要插入的数据；默认axis=None：先把数组展平成一维再插入
a = np.array([[1, 2], [3, 4], [5, 6]])
# 默认展平插入
print(np.insert(a, 1, [11, 22]))
print('-' * 50)
# 按行插入（insert可以一维，但是append必须二维）
print(np.insert(a, 1, [11, 22], axis=0))
print('-' * 50)
# 按列插入
print(np.insert(a, 1, [33, 44, 55], axis=1))
print('-' * 50)
# 如果只有一个元素值11，则会将11在0轴复制展开
print(np.insert(a, 1, 11, axis=0))
print('-' * 50)
# 所有插入操作都是返回新数组，原数组不发生变化
print(a)

[ 1 11 22  2  3  4  5  6]
--------------------------------------------------
[[ 1  2]
 [11 22]
 [ 3  4]
 [ 5  6]]
--------------------------------------------------
[[ 1 33  2]
 [ 3 44  4]
 [ 5 55  6]]
--------------------------------------------------
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]


In [86]:
# np.delete(arr, obj, axis=None)    arr：原数组；obj：要删除的下标/下标数组；默认axis=None：先把数组扁平化（拉成一维）再删除
import numpy as np
a = np.arange(12).reshape(3, 4)
print(a)
print('-' * 50)
# 默认展平删除，删除下标为5的数据
print(np.delete(a, 5))
print('-' * 50)
# 删除下标为1的行
print(np.delete(a, 1, axis=0))
print('-' * 50)
# 删除下标为1的列
print(np.delete(a, 1, axis=1))
print('-' * 50)
# 所有删除操作都是返回新数组，原数组不发生变化
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[ 0  1  2  3  4  6  7  8  9 10 11]
--------------------------------------------------
[[ 0  1  2  3]
 [ 8  9 10 11]]
--------------------------------------------------
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [100]:
# np.unique(a) 去重，返回数组中不重复的元素，并默认排序 
import numpy as np
a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

# 返回新数组，原数组不发生变化
print(np.unique(a))
print('-' * 50)
# np.unique(arr, return_index=False, return_inverse=False, return_counts=False, axis=None)
# return_index=True：返回唯一元素 + 首次出现下标；vals, idx = np.unique(a, return_index=True)
u, idx = np.unique(a, return_index=True)
print(u)
print(idx)
print('-' * 50)
# return_counts=True：返回唯一元素 + 每个元素出现次数；vals, cnt = np.unique(a, return_counts=True)
u, cnt = np.unique(a, return_counts=True)
print(u)
print(cnt)
print('-' * 50)
# return_inverse=True：返回唯一元素 + 映射下标（可还原原数组）；vals, inv = np.unique(a, return_inverse=True)   recover = vals[inv] 还原原始数组
u, inv = np.unique(a, return_inverse=True)
print(u)                            # [2 5 6 7 8 9]
print(inv)                      # [1 0 2 0 3 1 2 5 4 0]     这里的数据是原数据 a 在 u 中的下标

[2 5 6 7 8 9]
--------------------------------------------------
[2 5 6 7 8 9]
[1 0 2 4 8 7]
--------------------------------------------------
[2 5 6 7 8 9]
[3 2 2 1 1 1]
--------------------------------------------------
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 5 4 0]


# numpy的数学运算

In [109]:
import numpy as np
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
print(score.shape)
print('-' * 50)

# 1. 获取所有数据最大值
result = np.max(score)
print(result)
print('-' * 50)

# 2. 获取某一个轴上的数据最大值，对应的轴就消失
# 每行的各列求最大值
result = np.max(score, axis=1)
print(result)           # [88 82 81]
print('-' * 50)

# 3. 获取所有数据最小值
result = np.min(score)
print(result)
print('-' * 50)

# 4. 获取某一个轴上的数据最小值
# 各列的每行求最小值
result = np.min(score, axis=0)
print(result)           # [75 81]
print('-' * 50)

# 5. 数据的比较
# np.maximum(x1, x2)    逐元素进行比较，取两者中较大的值
result = np.maximum([-2, -1, 0, 1, 2], 0)
print(result)
# np.minimum(x1, x2)    逐元素进行比较，取两者中较小值
result = np.minimum([-2, -1, 0, 1, 2], 0)
print(result)
# 对应元素进行比较，取两者较大值；接受的两个参数可以大小一致，当第二个参数x2只是一个单独的值时，其实用到了维度的广播机制
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)

[[80 88]
 [82 81]
 [75 81]]
(3, 2)
--------------------------------------------------
88
--------------------------------------------------
[88 82 81]
--------------------------------------------------
75
--------------------------------------------------
[75 81]
--------------------------------------------------
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]


In [115]:
# 6. 求平均值
# 获取所有数据的平均值
result = np.mean(score)
print(result)
print('-' * 50)

# 各列的每行求均值
result = np.mean(score, axis=0)
print(result)
print('-' * 50)

# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('-' * 50)

# cumsum = cumulative sum累加和（前缀和）
'''
[1, 2, 3]------>	|1	   |2	  |3	|
[4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(axis=0))
print('-' * 50)
'''
[1, 2, 3]------>	|1	|2+1	|3+2+1	|
[4, 5, 6]------>	|4	|4+5	|4+5+6	|
'''
print(arr.cumsum(axis=1))

# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

81.16666666666667
--------------------------------------------------
[79.         83.33333333]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[1 2 3]
 [5 7 9]]
--------------------------------------------------
[[ 1  3  6]
 [ 4  9 15]]


In [119]:
print(score)
print('-' * 50)
# 8. argmin求最小值索引（argument of minimum：找出最小值所在的下标）
# 每列的各行中最小值索引
result = np.argmin(score, axis=0)
# 每列的各行中的最小值
res = np.min(score, axis=0)
print(result, res)
print('-' * 50)

# 9. 求每一列标准差（这里是总体标准差 standard deviation）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大。
# 一个较小的标准差，代表这些数据较接近平均值反映出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score, axis=0)
print(result)
print('-' * 50)

# 10. 极值(peak to peak：最大值与最小值的差)
result = np.ptp(score, axis=None)
print(result)

[[80 88]
 [82 81]
 [75 81]]
--------------------------------------------------
[2 1] [75 81]
--------------------------------------------------
[2.94392029 3.29983165]
--------------------------------------------------
13


In [121]:
t = np.arange(30).reshape(10, 3)
print(t)
# 求每列各行均值
np.mean(t, axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


array([13.5, 14.5, 15.5])

# 数组的拼接

In [123]:
# 有时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np

# 1. 根据轴连接的数组序列，concatenate没有改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
# 要求a，b两个数组的维度相同
print('沿轴 0 连接两个数组：')
print(np.concatenate((a, b), axis=0))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [124]:
print('沿轴 1 连接三个数组：')
print(np.concatenate((a, b, c), axis=1))

沿轴 1 连接两个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [127]:
# todo 维度堆叠，axis=1 指定“新增维度的位置”：axis=0 是第一个维度，axis=1 是第二个维度
print(np.stack((a, b, c), axis=1))
print(np.stack((a, b, c), axis=1).shape)    # stack会增加维度

[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]
(2, 3, 2)


In [130]:
# 2. 根据轴进行堆叠，二维会变成三维
arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
# print(arrays)
print(len(arrays))
print('沿轴 0 连接两个数组：')
result0 = np.stack(arrays, axis=0)
print(result0.shape)
print(result0)

10
沿轴 0 连接两个数组：
(10, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [129]:
print('-' * 50)
print('沿轴 1 连接两个数组：')
print(arrays[0])
result1 = np.stack(arrays, axis=1)
print(result1.shape)        # (3, 10, 4)
print(result1)

--------------------------------------------------
沿轴 1 连接两个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 10, 4)
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]]


In [131]:
print('-' * 50)
print('沿轴 2 连接两个数组：这里 -1 和 2 是等价的')
result2 = np.stack(arrays, axis=-1)
print(arrays[0])
print(result2.shape)
print(result2)

--------------------------------------------------
沿轴 2 连接两个数组：这里 -1 和 2 是等价的
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 10)
[[[ 0  0  0  0  0  0  0  0  0  0]
  [ 1  1  1  1  1  1  1  1  1  1]
  [ 2  2  2  2  2  2  2  2  2  2]
  [ 3  3  3  3  3  3  3  3  3  3]]

 [[ 4  4  4  4  4  4  4  4  4  4]
  [ 5  5  5  5  5  5  5  5  5  5]
  [ 6  6  6  6  6  6  6  6  6  6]
  [ 7  7  7  7  7  7  7  7  7  7]]

 [[ 8  8  8  8  8  8  8  8  8  8]
  [ 9  9  9  9  9  9  9  9  9  9]
  [10 10 10 10 10 10 10 10 10 10]
  [11 11 11 11 11 11 11 11 11 11]]]


In [132]:
# 3. 矩阵垂直拼接，vstack没有增加维数，类似于concatenate     ---vertical
v1 = [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

# 4. 矩阵水平拼接，类似于concatenate horizontal
v1 = [[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


# 分割

In [133]:
# 1. 将数组分割成多个子数组
# np.split(arr, indices_or_sections, axis)  待切分数组；均分份数；沿着哪个轴分割
import numpy as np
arr = np.arange(12).reshape(4, 3)
print(arr)
# 将数组arr按轴 1 均匀分成 3 份
b = np.split(arr, 3, axis=1)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [134]:
b[0].shape

(4, 1)

In [136]:
b = np.split(arr, 4, axis=0)
print(b)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [137]:
# 虽然水平但是垂直分成3份
c = np.hsplit(arr, 3)
print(c)    # c是列表
print(c[0].shape)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [138]:
d = np.random.random((2, 6))
print(d)

[[0.08885135 0.0376669  0.65686242 0.1827772  0.12539138 0.71250339]
 [0.12705815 0.88733921 0.85048928 0.34227992 0.16046065 0.53737868]]


In [139]:
# 2. numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组
harr = np.floor(10 * np.random.random((2, 6)))
print('原array：')
print(harr)

原array：
[[9. 3. 3. 5. 9. 1.]
 [1. 6. 2. 3. 3. 1.]]


In [141]:
# 3. numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4, 4)

print('第一个数组：')
print(a)
print('-' * 50)

# 很奇怪，虽然垂直但水平分割
b = np.vsplit(a, 2)
print(b)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------------------------------------
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# numpy的 inf 和 nan

In [142]:
# inf: infinity  Nan: Not a number（表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据）
import numpy as np
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [143]:
# 并且 np.nan != np.nan   结果是 True
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1      # nan和其他数运算的结果都是nan

False
True
True


nan

In [158]:
# 判断数组中nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将数组中行索引为3、列索引为4 这个位置的元素设置为np.nan(Not a Number，非数值，即缺失值、无效值)
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [159]:
# 可以使用 np.count_nonzero() 来判断非零个数
print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
# 统计nan个数
print(np.count_nonzero(t != t))

23
[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [161]:
# 生成和 t 同形状的布尔数组：元素NaN -> True，正常数字 -> False
print(np.isnan(t))
# 布尔索引，选中所有NaN位置，把所有NaN改成0
t[np.isnan(t)] = 0
print(t)

[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [164]:
# ------------------------练习：处理数组中的nan
t = np.arange(24).reshape(4, 6).astype('float')

# 将数组中一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-' * 50)

print(t.shape)              # (4, 6)
print(type(t.shape))        # <class 'tuple'>
print(id(t))
print('-' * 50)

# 遍历每一列，然后判断每一列是否有nan
# t.shape[0] = 行数；t.shape[1] = 列数   t.shape = (4, 6)    t.shape[0] = 4     t.shape[1] = 6
for i in range(t.shape[1]):
    # 获取当前列数据
    temp_col = t[:, i]
    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num > 0:
        # 将这一列不为nan的数据拿出来，并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值（np.isnan(temp_col) -> 同形状布尔型数组）
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
        
        
print(t)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------
(4, 6)
<class 'tuple'>
4487770352
--------------------------------------------------
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
4487770352


In [165]:
print(np.inf == np.inf)
np.inf

True


inf

In [171]:
# np.nan 和任何数据运算的结构都是nan
t = np.arange(24).reshape(4, 6).astype('float')

# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-' * 50)

t1 = np.arange(24).reshape(4, 6).astype('float')
print(t1)
print('-' * 50)
t1 + t

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------


array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [172]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])      # 1除0就会得到inf

[-1  0]
-inf


/var/folders/pb/p_cly9gj3xv6l7083h32ln_80000gn/T/ipykernel_9869/2114806057.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])


In [173]:
np.nan + np.inf

nan

# 转置和轴滚动

In [175]:
# 对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)
print('-' * 50)

# 就是线性代数里的转置
print(np.transpose(a))
# 这里同样，转置是生成新的数组，而原数组不发生任何变化
print(a)
print('-' * 50)

# 与transpose一致
a = np.arange(12).reshape(3, 4)
print(a)
print(a.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [177]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
print(t1)
print('-' * 50)

# axis（单数）-> axes（复数）
# swapaxes只能交换两个轴，而transpose可以交换任意多个轴
re1 = t1.swapaxes(1, 0)
print(re1)
print(re1.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
(6, 4)


In [178]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
# 0轴不变，1轴与2轴相互交换
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)
print(t3)

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)
[[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]


In [179]:
# 数组的轴滚动，swapaxes每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
# np.rollaxis(a, 2).shape
# 抽走轴3（其余轴相对顺序保持不变），将轴3放置在轴1的位置；故位置变为从 (0, 1, 2, 3) -> (0, 3, 1, 2)
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [182]:
# 数据拷贝，copy()和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
print(id(b))
print(id(a))
a

4599398288
4599398000


array([[1, 2, 3],
       [1, 2, 3]])

In [181]:
b[0, 0] = 3
print(b)
a

[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [183]:
# 随机数生成，直接传入各维度大小，不需要元组
arr = np.random.rand(2, 3, 4)
# 必须传 size=元组
d = np.random.random(size=(2, 3, 4))
print(arr)

[[[0.78409815 0.7425687  0.06582729 0.7788492 ]
  [0.23339052 0.67464135 0.42577786 0.37896643]
  [0.1889115  0.84752757 0.71598296 0.38839086]]

 [[0.86189665 0.06167193 0.00762626 0.05539314]
  [0.26472222 0.87447957 0.72616026 0.98315042]
  [0.73167139 0.77276788 0.80284743 0.06900418]]]


In [184]:
# 1. 均匀分布的随
names = 'zhangsan,listi,wangwu,zhaoliu,sunqi'
# 写入文件
# open('names.csv', 'w')：打开文件names.csv；'w'=write写入模式；文件不存在 -> 创建文件，文件存在：直接覆盖原有内容
# with ... as f: 上下文管理器：代码块结束自动关闭文件，不用手写f.close()；即使中途报错，文件也能正常释放
with open('names.csv', 'w') as f:
    f.write(names)
    f.write('\n')
    f.write('12,23,34,45,56')
    
# csv: comma-separated values，逗号分隔值文件，是一种极简的纯文本表格文件；只用逗号把每一格数据隔开，纯文字，体积极小，所有软件通用